"""
Module: enigma_reason/observability/llm_cache.py

A content addressed cache in front of the language model.

Level 9 runs sixteen configurations across four regimes at five seeds. With
up to three model calls per analysis this is the dominant cost of the whole
study, and most of those calls ask the identical question.

Key choice. The brief specifies a key derived from the assembled context
dict. The cache implemented here keys on the fully assembled prompt instead,
because the context dict is not sufficient to identify the request: the prompt
also embeds the prior hypotheses being refined, so two iterations sharing a
context dict but carrying different prior beliefs would collide and the cache
would return an answer to a question that was not asked. The prompt is a
strict superset of the context, so this key is sound wherever the narrower one
would have been and correct where it would not.

What this predicts about the hit rate. The ablation varies what happens after
hypotheses are generated, not the context that produces them, so the first
iteration of a given situation assembles a byte identical prompt in every one
of the sixteen configurations and is a guaranteed hit for fifteen of them.
Later iterations embed the confidences that the ablated mechanisms have by
then altered, so they hit only across configurations that agree on the
mechanisms which touch confidence. The measured rates are reported in
results/level6 rather than asserted here.
"""

from __future__ import annotations

import hashlib
import json
import logging
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

KEY_LENGTH = 32


def prompt_key(prompt: str, model: str = "") -> str:
    """Return the cache key for one request.

    The model name participates so that switching model does not silently
    serve answers generated by a different one.
    """
    digest = hashlib.sha256()
    digest.update(model.encode("utf-8"))
    digest.update(b"\x00")
    digest.update(prompt.encode("utf-8"))
    return digest.hexdigest()[:KEY_LENGTH]


def context_key(context: dict[str, Any], model: str = "") -> str:
    """Return a key over a context dict alone, for reporting reuse potential.

    This is the key the brief describes. It is recorded alongside the prompt
    key so the study can report how much additional reuse a context only key
    would appear to offer, without ever serving a response from it.
    """
    payload = json.dumps(context, sort_keys=True, separators=(",", ":"), default=str)
    return prompt_key(payload, model)


@dataclass
class CacheStats:
    """Counts describing one cache's lifetime."""

    hits: int = 0
    misses: int = 0
    writes: int = 0
    errors: int = 0

    @property
    def lookups(self) -> int:
        """Total requests presented to the cache."""
        return self.hits + self.misses

    @property
    def hit_rate(self) -> float:
        """Fraction of requests served without calling the model."""
        return self.hits / self.lookups if self.lookups else 0.0

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON serialisable view."""
        return {
            "hits": self.hits,
            "misses": self.misses,
            "writes": self.writes,
            "errors": self.errors,
            "lookups": self.lookups,
            "hit_rate": round(self.hit_rate, 4),
        }


@dataclass(frozen=True)
class CachedResponse:
    """Stands in for a langchain message, exposing only what nodes read."""

    content: str


class ResponseCache:
    """Prompt keyed store of model responses, optionally persisted to disk.

    Args:
        path: JSON file holding the cache between processes. When omitted the
            cache lives only for the lifetime of the object, which is what the
            unit tests want and what a single ad hoc run needs.
        model: Model identifier folded into every key.
    """

    def __init__(self, path: str | Path | None = None, model: str = "") -> None:
        self.path = Path(path) if path else None
        self.model = model
        self.stats = CacheStats()
        self._entries: dict[str, str] = {}
        self._lock = threading.Lock()
        self._load()

    def _load(self) -> None:
        """Read a persisted cache, treating any failure as an empty cache."""
        if self.path is None or not self.path.is_file():
            return
        try:
            payload = json.loads(self.path.read_text(encoding="utf-8"))
            entries = payload.get("entries", {})
            if isinstance(entries, dict):
                self._entries = {str(k): str(v) for k, v in entries.items()}
            logger.info("Response cache loaded with %d entries", len(self._entries))
        except Exception as exc:
            self.stats.errors += 1
            logger.warning("Response cache could not be read from %s: %s", self.path, exc)

    def save(self) -> None:
        """Persist the cache, swallowing any failure."""
        if self.path is None:
            return
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self._lock:
                payload = {"model": self.model, "entries": dict(self._entries)}
            self.path.write_text(json.dumps(payload), encoding="utf-8")
        except Exception as exc:
            self.stats.errors += 1
            logger.warning("Response cache could not be written to %s: %s", self.path, exc)

    def get(self, prompt: str) -> str | None:
        """Return a cached response, or None on a miss."""
        key = prompt_key(prompt, self.model)
        with self._lock:
            value = self._entries.get(key)
            if value is None:
                self.stats.misses += 1
            else:
                self.stats.hits += 1
        return value

    def put(self, prompt: str, response: str) -> None:
        """Store a response against its prompt."""
        key = prompt_key(prompt, self.model)
        with self._lock:
            self._entries[key] = response
            self.stats.writes += 1

    def __len__(self) -> int:
        with self._lock:
            return len(self._entries)


class _CachingModel:
    """Wraps one model instance so repeated prompts skip the network."""

    def __init__(self, inner: Any, cache: ResponseCache) -> None:
        self._inner = inner
        self._cache = cache

    def invoke(self, prompt: str) -> CachedResponse:
        """Return a cached response when the prompt has been seen before."""
        cached = self._cache.get(prompt)
        if cached is not None:
            return CachedResponse(content=cached)
        response = self._inner.invoke(prompt)
        text = response.content if hasattr(response, "content") else str(response)
        self._cache.put(prompt, text)
        return CachedResponse(content=text)


class CachingLLMFactory:
    """Factory decorator that puts a response cache in front of a model.

    The inner factory is called lazily and at most once, because constructing
    a Gemini client per graph node is pure overhead when every prompt is
    already cached, and because a fully cached run must not require an API key
    at all.

    Args:
        inner_factory: The factory to wrap, typically the default Gemini one.
        cache: The store to consult.
    """

    def __init__(self, inner_factory: Callable[[], Any], cache: ResponseCache) -> None:
        self._inner_factory = inner_factory
        self._cache = cache
        self._model: Any | None = None
        self._lock = threading.Lock()

    @property
    def stats(self) -> CacheStats:
        """Counts for the underlying cache."""
        return self._cache.stats

    def __call__(self) -> _CachingModel:
        return _CachingModel(_LazyModel(self), self._cache)

    def _resolve(self) -> Any:
        """Construct the wrapped model on first genuine need."""
        with self._lock:
            if self._model is None:
                self._model = self._inner_factory()
            return self._model


class _LazyModel:
    """Defers construction of the real model until a prompt actually misses."""

    def __init__(self, factory: CachingLLMFactory) -> None:
        self._factory = factory

    def invoke(self, prompt: str) -> Any:
        """Build the real model if needed and forward the prompt to it."""
        return self._factory._resolve().invoke(prompt)
